galaxy_info:
  author: Gary López
  description: Role to get information of servers from openstack

  license: GPLv3

  min_ansible_version: 1.2

  platforms:
  - name: EL
    versions:
    - 7

  galaxy_tags:
    - openstack

dependencies: []