- hosts: workstation
  gather_facts: true
  roles:
  - osp-facts

# Setup front-end load balancer tier

- name: setup load-balancer tier
  hosts: frontends
#  become: yes
  gather_facts: false
  roles:
    - {name: base-config, tags: base-config}
    - {name: lb-tier, tags: [lbs, haproxy]}
  pre_tasks:
  - name: get the username running the deploy
    become: false
    local_action: command {{ _command }}
    register: username_on_the_host

  - debug: var=username_on_the_host

# Setup application servers tier

- name: setup app tier
  hosts: apps
  become: yes
  gather_facts: false
  roles:
    - {name: base-config, tags: base-config}
    - {name: app-tier, tags: [apps, tomcat]}

# Setup database tier

- name: setup database tier
  become: yes
  hosts: appdbs
  roles:
    - {name: base-config, tags: base-config}
    - {name: db-tier, tags: [dbs, postgres]}
