galaxy_info:
    author: Gary López
    description: Role to configure repository for roles to install App Tier application

    license: GPLv3

    min_ansible_version: 1.2

    platforms:
    - name: EL
      versions:
      - 7

    galaxy_tags:
      - repositories

dependencies: []